/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectoop_v1;

import static projectoop_v1.RoomDetail.receipt;

/**
 *
 * @author FIKRI DIN
 */
public class ReceiptInterface extends javax.swing.JFrame {

    /** Creates new form ReceiptInterface */
    static Customer[] cust;
    static Receipt[] receipt;
    static int rooms;
    public ReceiptInterface() {
        initComponents();
        rooms = BookingForm.rooms;
        receipt = BookingForm.receipt;
        cust = BookingForm.cust;
        for (int i = 0; i < 140; i++){
            if (cust[i].getName().equals(BookingForm.name)){
                lblRecDate.setText((receipt[i].receiptDate).toString());
                //lblBookedRoom.setText(receipt[i].printRoom());
                lblCustName.setText(cust[i].getName());
                lblInDate.setText(cust[i].getCheckIn());
                lblOutDate.setText(cust[i].getCheckOut());
                double total = receipt[i].getTotalPrice();
                String price = Double.toString(receipt[i].getTotalPrice());
                lblTotPrice.setText("RM " + price);
                String day = Integer.toString(cust[i].getDays());
                lblTotDays.setText(day);
            }
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblReceipt = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblRecDate = new javax.swing.JLabel();
        lblRoom = new javax.swing.JLabel();
        lblBookedRoom = new javax.swing.JLabel();
        lblDetail = new javax.swing.JLabel();
        lblIn = new javax.swing.JLabel();
        lblOut = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblDays = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCustName = new javax.swing.JLabel();
        lblInDate = new javax.swing.JLabel();
        lblOutDate = new javax.swing.JLabel();
        lblTotPrice = new javax.swing.JLabel();
        lblTotDays = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblReceipt.setFont(new java.awt.Font("Tiger Expert", 1, 30)); // NOI18N
        lblReceipt.setText("Receipt");

        lblDate.setText("Receipt Date          :");

        lblRoom.setText("Room:                    :");

        lblDetail.setText("Booker Detail");

        lblIn.setText("Check-In Date       :");

        lblOut.setText("Check-Out Date    :");

        lblPrice.setText("Total Price             :");

        lblDays.setText("Total Days             :");

        lblName.setText("Name                     :");

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(lblReceipt)
                        .add(184, 184, 184))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblDate)
                                    .add(lblRoom))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblBookedRoom)
                                    .add(lblRecDate)))
                            .add(lblDetail)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblIn)
                                    .add(lblOut)
                                    .add(lblPrice)
                                    .add(lblDays)
                                    .add(lblName))
                                .add(8, 8, 8)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblCustName)
                                    .add(lblInDate)
                                    .add(lblOutDate)
                                    .add(lblTotPrice)
                                    .add(lblTotDays))))
                        .add(220, 220, 220))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(btnDone)
                        .add(202, 202, 202))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(lblReceipt)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDate)
                    .add(lblRecDate))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblRoom)
                    .add(lblBookedRoom))
                .add(42, 42, 42)
                .add(lblDetail)
                .add(27, 27, 27)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblName)
                    .add(lblCustName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblIn)
                    .add(lblInDate))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblOut)
                    .add(lblOutDate))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblPrice)
                    .add(lblTotPrice))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDays)
                    .add(lblTotDays))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 287, Short.MAX_VALUE)
                .add(btnDone)
                .add(22, 22, 22))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(260, 260, 260)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new userValidation().setVisible(true);
        
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiptInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiptInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiptInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiptInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiptInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBookedRoom;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDays;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblIn;
    private javax.swing.JLabel lblInDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOut;
    private javax.swing.JLabel lblOutDate;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRecDate;
    private javax.swing.JLabel lblReceipt;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblTotDays;
    private javax.swing.JLabel lblTotPrice;
    // End of variables declaration//GEN-END:variables

}
