/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectoop_v1;

/**
 *
 * @author FIKRI DIN
 */
public class RoomDetail extends javax.swing.JFrame {

    static Room[] room;
    static Receipt[] receipt;
    static String name;
    static int rooms;
    static Customer[] cust;
    int k;
    /** Creates new form RoomDetail */
    public RoomDetail() {
        k = 0;
        cust = BookingForm.cust;
        rooms = BookingForm.rooms;
        receipt = BookingForm.receipt;
        name = BookingForm.name;
        room = userValidation.room;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lblType = new javax.swing.JLabel();
        radBtnSingle = new javax.swing.JRadioButton();
        radBtnPre = new javax.swing.JRadioButton();
        lblPack = new javax.swing.JLabel();
        radBtnYes = new javax.swing.JRadioButton();
        radBtnNo = new javax.swing.JRadioButton();
        pnlFood = new javax.swing.JPanel();
        lblFood = new javax.swing.JLabel();
        lblPackA = new javax.swing.JLabel();
        lblPackB = new javax.swing.JLabel();
        lblPackC = new javax.swing.JLabel();
        combPack = new javax.swing.JComboBox<>();
        lblChoose = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblType.setText("Room Type:");

        buttonGroup1.add(radBtnSingle);
        radBtnSingle.setText("Single");
        radBtnSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnSingleActionPerformed(evt);
            }
        });

        buttonGroup1.add(radBtnPre);
        radBtnPre.setText("Presidential");
        radBtnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnPreActionPerformed(evt);
            }
        });

        lblPack.setText("Do you want food package:");
        lblPack.setEnabled(false);

        buttonGroup2.add(radBtnYes);
        radBtnYes.setText("Yes");
        radBtnYes.setToolTipText("");
        radBtnYes.setEnabled(false);
        radBtnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnYesActionPerformed(evt);
            }
        });

        buttonGroup2.add(radBtnNo);
        radBtnNo.setText("No");
        radBtnNo.setEnabled(false);
        radBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnNoActionPerformed(evt);
            }
        });

        pnlFood.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFood.setText("List Food Package:");
        lblFood.setEnabled(false);

        lblPackA.setText("A. Breakfast - Lunch - Dinner (RM100.30)");
        lblPackA.setEnabled(false);

        lblPackB.setText("B. Breakfast - Lunch (RM60.80)");
        lblPackB.setEnabled(false);

        lblPackC.setText("C.Breakfast (RM30.50)");
        lblPackC.setEnabled(false);

        combPack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select a package -", "Package A", "Package B", "Package C" }));
        combPack.setEnabled(false);

        lblChoose.setText("Choose Package:");
        lblChoose.setEnabled(false);

        org.jdesktop.layout.GroupLayout pnlFoodLayout = new org.jdesktop.layout.GroupLayout(pnlFood);
        pnlFood.setLayout(pnlFoodLayout);
        pnlFoodLayout.setHorizontalGroup(
            pnlFoodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFoodLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .add(pnlFoodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlFoodLayout.createSequentialGroup()
                        .add(pnlFoodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlFoodLayout.createSequentialGroup()
                                .add(44, 44, 44)
                                .add(lblFood))
                            .add(lblPackB)
                            .add(lblPackC)
                            .add(lblChoose))
                        .add(100, 100, 100))
                    .add(pnlFoodLayout.createSequentialGroup()
                        .add(lblPackA)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlFoodLayout.createSequentialGroup()
                        .add(combPack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(98, 98, 98))))
        );
        pnlFoodLayout.setVerticalGroup(
            pnlFoodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFoodLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(lblFood)
                .add(18, 18, 18)
                .add(lblPackA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblPackB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblPackC)
                .add(29, 29, 29)
                .add(lblChoose)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(combPack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(radBtnYes)
                                .add(18, 18, 18)
                                .add(radBtnNo))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jPanel2Layout.createSequentialGroup()
                                    .add(radBtnSingle)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(radBtnPre))
                                .add(lblType)
                                .add(lblPack)))
                        .add(110, 110, 110))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlFood, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(btnNext)
                        .add(150, 150, 150)))
                .add(148, 148, 148))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(0, 34, Short.MAX_VALUE)
                .add(lblType)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radBtnSingle)
                    .add(radBtnPre))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lblPack)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radBtnYes)
                    .add(radBtnNo))
                .add(32, 32, 32)
                .add(pnlFood, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnNext)
                .add(21, 21, 21))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(55, 55, 55)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radBtnSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnSingleActionPerformed
        // TODO add your handling code here:
        
        lblPack.setEnabled(true);
        radBtnYes.setEnabled(true);
        radBtnNo.setEnabled(true);
        
        lblFood.setEnabled(false);
        lblPackA.setEnabled(false);
        lblPackB.setEnabled(false);
        lblPackC.setEnabled(false);
        lblChoose.setEnabled(false);
        combPack.setEnabled(false);
        
    }//GEN-LAST:event_radBtnSingleActionPerformed

    private void radBtnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnPreActionPerformed
        // TODO add your handling code here:
        
        lblPack.setEnabled(false);
        radBtnYes.setEnabled(false);
        radBtnNo.setEnabled(false);
        
        lblFood.setEnabled(true);
        lblPackA.setEnabled(true);
        lblPackB.setEnabled(true);
        lblPackC.setEnabled(true);
        lblChoose.setEnabled(true);
        combPack.setEnabled(true);
        
    }//GEN-LAST:event_radBtnPreActionPerformed

    private void radBtnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnYesActionPerformed
        // TODO add your handling code here:
        
        lblFood.setEnabled(true);
        lblPackA.setEnabled(true);
        lblPackB.setEnabled(true);
        lblPackC.setEnabled(true);
        lblChoose.setEnabled(true);
        combPack.setEnabled(true);
        
    }//GEN-LAST:event_radBtnYesActionPerformed

    private void radBtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnNoActionPerformed
        // TODO add your handling code here:
        
        lblFood.setEnabled(false);
        lblPackA.setEnabled(false);
        lblPackB.setEnabled(false);
        lblPackC.setEnabled(false);
        lblChoose.setEnabled(false);
        combPack.setEnabled(false);
        
    }//GEN-LAST:event_radBtnNoActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:

        char pack = '\0';
        int i = 0;
        
        
        if (radBtnPre.isSelected()){
            //create presidential
            if (combPack.getSelectedItem().toString().equals("- Select a package -")){
                combPack.requestFocus();
            } else {
                switch (combPack.getSelectedItem().toString()) {
                    case "Package A":
                        pack = 'A';
                        break;
                    case "Package B":
                        pack = 'B';
                        break;
                    case "Package C":
                        pack = 'C';
                        break;
                    default:
                        pack = 'D';
                        break;
                }
                for (i = 10; i < 20; i++){
                    if (room[i].status.equals("Available")){
                        room[i] = new Presidential(room[i].getRoomNumber(), name, pack);
                        room[i].setStatus("Occupied");
                        for (int j = 0; j < 20; j++){
                            for (int a = 0; a < 140; a++){
                                if (receipt[j].getCustomer().getName().equals(cust[a].getName())){
                                    receipt[j].setRoomBooked(room[i],k);
                                    a = 140;
                                    j = 20;
                                }
                            }
                        }
                        i = 20;
                        k++;
                        this.setVisible(false);
                        if (k < rooms){
                            new RoomDetail().setVisible(true);
                        } else {
                            new ReceiptInterface().setVisible(true);
                        }
                        
                    }
                }
            }
            
        } else if (radBtnSingle.isSelected()){
            
            if (!radBtnYes.isSelected() && !radBtnNo.isSelected()){
                lblFood.requestFocus();
            } else if (radBtnYes.isSelected()){
                if (combPack.getSelectedItem().toString().equals("- Select a package -")){
                    combPack.requestFocus();
                } else {
                    switch (combPack.getSelectedItem().toString()) {
                        case "Package A":
                            pack = 'A';
                            break;
                        case "Package B":
                            pack = 'B';
                            break;
                        case "Package C":
                            pack = 'C';
                            break;
                        default:
                            pack = 'D';
                            break;
                    }                    
                }
            } else {
                pack = '\0';
            }
            for (i = 0; i < 10; i++){
                if (room[i].status.equals("Available")){
                    Food food = new Food(pack);
                    room[i] = new Single(room[i].getRoomNumber(), food, name);
                    room[i].setStatus("Occupied");
                    for (int j = 0; j < 20; j++){
                        for (int a = 0; a < 140; a++){
                            if (receipt[j].getCustomer().getName().equals(cust[a].getName())){
                                receipt[j].setRoomBooked(room[i],k);
                                a = 140;
                                j = 20;
                            }
                        }
                    }
                    i = 10;
                    k++;
                    this.setVisible(false);
                    if (k < rooms){
                        new RoomDetail().setVisible(true);
                    } else {
                        new ReceiptInterface().setVisible(true);
                    }
                        
                }
            }
                    
            
            
        } else {
            lblType.requestFocus();
        }
        
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomDetail().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> combPack;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel lblChoose;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblPack;
    private javax.swing.JLabel lblPackA;
    private javax.swing.JLabel lblPackB;
    private javax.swing.JLabel lblPackC;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel pnlFood;
    private javax.swing.JRadioButton radBtnNo;
    private javax.swing.JRadioButton radBtnPre;
    private javax.swing.JRadioButton radBtnSingle;
    private javax.swing.JRadioButton radBtnYes;
    // End of variables declaration//GEN-END:variables

}
