/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectoop_v1;

import javax.swing.JFrame;

/**
 *
 * @author FIKRI DIN
 */
public class userValidation extends javax.swing.JFrame {

    static Customer[] cust;
    static Employee[] emp;
    static Room[] room;
        /** Creates new form userValidation
     * @param cust */
    public userValidation() {
        cust = new Customer[140]; //20 rooms * 7 days
        emp = new Employee[20];
        room = new Room[20];
        
        for (int j = 0; j < 140; j++){
            cust[j] = new Customer("null", 0, "null", "null", "null", "null", "null");
        }
        
//        for (int j = 0; j < 20; j++){
//            receipt[j] = new Receipt(null);
//        }
        
        room[0] = new Single("S01","null");
        room[1] = new Single("S02","null");
        room[2] = new Single("S03","null");
        room[3] = new Single("S04","null");
        room[4] = new Single("S05","null");
        room[5] = new Single("S06","null");
        room[6] = new Single("S07","null");
        room[7] = new Single("S08","null");
        room[8] = new Single("S09","null");
        room[9] = new Single("S10","null");
        room[10] = new Presidential("P01","null",'\0');
        room[11] = new Presidential("P02","null",'\0');
        room[12] = new Presidential("P03","null",'\0');
        room[13] = new Presidential("P04","null",'\0');
        room[14] = new Presidential("P05","null",'\0');
        room[15] = new Presidential("P06","null",'\0');
        room[16] = new Presidential("P07","null",'\0');
        room[17] = new Presidential("P08","null",'\0');
        room[18] = new Presidential("P09","null",'\0');
        room[19] = new Presidential("P10","null",'\0');
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radBtnCust = new javax.swing.JRadioButton();
        radBtnEmp = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        radBtnCust.setText("Customer");
        radBtnCust.setActionCommand("Customer");
        radBtnCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnCustActionPerformed(evt);
            }
        });

        radBtnEmp.setText("Employee");
        radBtnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnEmpActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 36)); // NOI18N
        lblWelcome.setText("Welcome to Pekan Hotel ");

        lblType.setText("Select your user type:");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(lblType)
                        .add(286, 286, 286))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(radBtnEmp)
                            .add(radBtnCust))
                        .add(309, 309, 309))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(btnNext)
                        .add(317, 317, 317))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(lblWelcome)
                        .add(85, 85, 85))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(51, 51, 51)
                .add(lblWelcome)
                .add(48, 48, 48)
                .add(lblType)
                .add(18, 18, 18)
                .add(radBtnCust)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(radBtnEmp)
                .add(18, 18, 18)
                .add(btnNext)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(141, 141, 141)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radBtnCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnCustActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        
        if (radBtnCust.isSelected()){
            this.setVisible(false);
            new BookingForm().setVisible(true);
        } else if (radBtnEmp.isSelected()){
            this.setVisible(false);
            new EmployeeInterface().setVisible(true);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void radBtnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new userValidation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JRadioButton radBtnCust;
    private javax.swing.JRadioButton radBtnEmp;
    // End of variables declaration//GEN-END:variables

}
